### ISSUE TITLE
how is this different than https://github.com/sebastianbergmann/phpcov

### ISSUE THREAD

**Issue by tmotyl** [Nimut/phpunit-merger#11]
it seems that https://github.com/sebastianbergmann/phpcov also provides an option to merge coverage reports:
https://github.com/sebastianbergmann/phpcov#merging-exported-php-code-coverage-objects-stored-in-cov-files
How is then this package different from phpcov?

**Comment by IchHabRecht** [comment]
Hi @tmotyl,

As far as I can see, the phpcov package is not able to merge JUnit XML reports but only clover files.

**Comment by tmotyl** [comment]
thanks for the info!

**Comment by Potherca** [comment]
For the sake of completion, `phpcov` supports these formats:

```
  --clover <file>        Generate code coverage report in Clover XML format
  --cobertura <file>     Generate code coverage report in Cobertura XML format
  --crap4j <file>        Generate code coverage report in Crap4J XML format
  --html <directory>     Generate code coverage report in HTML format
  --php <file>           Export php-code-coverage object
  --text <file>          Generate code coverage report in text format
  --xml <directory>      Generate code coverage report in PHPUnit XML format
``` 

JUnit _could_ be one of the supported XML formats? :-/
