### ISSUE TITLE
Support output for multiple test suites

### ISSUE THREAD

**Issue by mbrodala** [Nimut/phpunit-merger#12]
ATM reports for multiple test suites are not supported.

With a single test suite the `--log-junit` output of PHPUnit looks like this:

```xml
<testsuites>
    <testsuite name="Foo" tests="10">
        <!-- ... -->
    </testsuite>
</testsuites>
```

However, with multiple test suites PHPUnit adds another grouping `<testsuite>` element:

```xml
<testsuites>
    <testsuite name="" tests="15">
        <testsuite name="Foo" tests="10">
            <!-- ... -->
        </testsuite>
        <testsuite name="Bar" tests="5">
            <!-- ... -->
        </testsuite>
    </testsuite>
</testsuites>
```

Since the `LogCommand` drops all test suites with an empty name this leads to all test suites being dropped.

See https://github.com/sebastianbergmann/phpunit/issues/2784

**Comment by IchHabRecht** [comment]
Hi @mbrodala,

Would you mind to test the attached pull request?

**Comment by mbrodala** [comment]
Tested and confirmed. :-)
