### ISSUE TITLE
PHP 8 support

### ISSUE THREAD

**Issue by Pi-George** [Nimut/phpunit-merger#16]
What the title says

**Comment by mbarbey** [comment]
After looking at the `travis` file, PHP 8 and 8.1 seem to be supported, but the `composer.json` seem to only allow up to 8.0.

Any plan to officially support up to 8.1 ?

**Comment by IchHabRecht** [comment]
Hi @mbarbey,

I think it is resolved in the current released version as composer defines a compability to "^8.0" which includes 8.1 as well.
