### ISSUE TITLE
Any plan to upgrade symfony/console version ?

### ISSUE THREAD

**Issue by mbarbey** [Nimut/phpunit-merger#22]
Sadly, this package can't be installed on a fresh Symfony 5.4 due to a conflict of version for the symfony/console dependency.
While Symfony 5.4 require to use symfony/console 6+, phpunit-merger require in other hand to be lower than 6.

Any plan to support newer version ?

**Comment by IchHabRecht** [comment]
Hi @mbarbey 

A new version 1.1.3 was just released with the support for current symfony packages.
