### ISSUE TITLE
Allow multiple type output

### ISSUE THREAD

**Issue by Jerome1337** [Nimut/phpunit-merger#4]
It would be nice to allow the merging command to create and output multiple type of reports.

**Comment by IchHabRecht** [comment]
Hi @Jerome1337,

Thank you for your proposal. Can you describe the difference from this ticket to the other one (#3) you already added? Are those the same or are this two separate feature requests? Thank you very much.

**Comment by Jerome1337** [comment]
Hi @IchHabRecht 

This one is another feature request than #3. 

#3 Is supposed to choose to return HTML report instead Clover one.

This one is to allow the merge command to render multiple types of reports in same time instead of one, for example:
- Clover and HTML
or
- Clover, HTML and Text

**Comment by IchHabRecht** [comment]
Hi @Jerome1337,

I created a pull request that solves your feature request. Would you mind to test #5?
